### ISSUE TITLE
Slack Integration

### ISSUE THREAD

**Issue by jatinsandilya** [revertinc/revert#211]
**Endpoints to be supported:** 

`GET https://api.revert.dev/chat/channels`: List all channels of the Slack workspace connected

`GET https://api.revert.dev/chat/users`: List all users of the Slack workspace connected 

`POST https://api.revert.dev/chat/message`: Create a message in a specific channel

**Comment by jatinsandilya** [comment]
**The flow for Slack will look like this:** 

- Our customer uses our SDK to provide a "Connect to Slack" button on their UI for their users.
- On clicking the button they will go through an OAuth flow and be able to connect their Slack workspace with our OAuth App.
- Once connected,  our customer will be able to use our APIs (endpoints mentioned) to work with the connected Slack workspace.

The starting point would be to just be able to connect the Slack workspace using Revert.

**Comment by ashutoshdhande** [comment]
@jatinsandilya let's do this

**Comment by jatinsandilya** [comment]
**Response structure for the two `GET` endpoints.** 

1. `GET https://api.revert.dev/chat/channels`: List all channels of the Slack workspace connected

`{
	"channels": [{
		"id": "123",
		"name": "engineering",
		"createdTime": "2022-08-24T04:12:21Z"
	}]
}`


2. `GET https://api.revert.dev/chat/users` : List all users of the Slack workspace connected

`{
	"users": [{
		"id": "123",
		"name": "harry",
		"createdTime": "2022-08-24T04:12:21Z"
	}]
}`

**Request structure for creating a message -** 

`POST https://api.revert.dev/chat/message`:  Create a message in a specific channel

`
{
	"message": {
		"text": "Hello, world!",
		"channelId": "123"
	}
}
`

**Response**

`
{
	"message": {
		"text": "Hello, world!",
		"channelId": "123"
	}
}
`

**Comment by jatinsandilya** [comment]
We need to paginate the results from the `GET` calls as well but that can step 2.

**Comment by ashutoshdhande** [comment]
Got it!!!

**Comment by ashutoshdhande** [comment]
@jatinsandilya, please review this [loom video](https://www.loom.com/share/57354696a2044916918bb9b884546e88?sid=8b6f4caf-8e4a-452c-babd-81322e8504c9). I'm unsure why it had some flickering. Tomorrow, I plan to prepare a pull request since I omitted certain middlewares and client-side aspects to prioritize the development of features. I will post further issue on discord so everyone can be on same page.
