### ISSUE TITLE
Discord Integration

### ISSUE THREAD

**Issue by jatinsandilya** [revertinc/revert#213]

**Comment by hrutik7** [comment]
hey
@jatinsandilya I like to work on this will that be fine ?

**Comment by jatinsandilya** [comment]
Absolutely! Assigned it to you

**Comment by jatinsandilya** [comment]
This will have the same API request/response structures as the Slack integration for reference: https://github.com/revertinc/revert/issues/211

**Comment by hrutik7** [comment]
sure study that too
