### ISSUE TITLE
Use docker-compose for deployment locally

### ISSUE THREAD

**Issue by jatinsandilya** [revertinc/revert#230]
Add a single command setup for local developement or deployment in a self-hosted environment

**Comment by rajdip-b** [comment]
Hey! Might I take up this issue?

**Comment by jatinsandilya** [comment]
@rajdip-b Yes please! We do have a docker compose setup but it could be better for sure. I'll assign it to you then.

**Comment by rajdip-b** [comment]
Hey @jatinsandilya, I went through the code and barely found anything to improve, rather than some rearrangements of the Dockerfile to reduce the build time. Should I just submit that PR?

**Comment by jatinsandilya** [comment]
This issue is closed with the latest changes 

@rajdip-b If you have suggestions on how to improve the build times for it, please do make a PR suggesting it! 🙌🏼
