### ISSUE TITLE
[REVER-23] Github issues support

### ISSUE THREAD

**Issue by jatinsandilya** [revertinc/revert#252]
To goal of this issue is to support Github as an integration within Revert APIs.

Github OAuth documentation: https://docs.github.com/en/apps/oauth-apps/building-oauth-apps/differences-between-github-apps-and-oauth-apps

Github API docs: https://docs.github.com/en/rest?apiVersion=2022-11-28 

Next steps:

* Familiarise yourself with the Github APIs
* Familiarise yourself with how Revert works
* Understand how we store OAuth credentials within Revert and make changes such that we can allow our users to be able to make a `connection` with a Github account
* _For Bonus 25 points_: create apis in Revert to get `issues` & `users` from a connected Github account

Ask us any questions you might have on our [discord](https://discord.com/invite/q5K5cRhymW).

**Comment by subhajit20** [comment]
hey @jatinsandilya, I want to work on this,
can you guide me on how to solve this?

**Comment by jatinsandilya** [comment]
@subhajit20 Happy to! Will add more details to the issue. In the meantime, feel free to join our discord where we can have a longer discussion on this. Assigning this to you for now.

**Comment by subhajit20** [comment]
> @subhajit20 Happy to! Will add more details to the issue. In the meantime, feel free to join our discord where we can have a longer discussion on this. Assigning this to you for now.

Sure

**Comment by jatinsandilya** [comment]
@subhajit20 Added more details into the issue. Lmk if you have any questions!

**Comment by hrutik7** [comment]
hey @subhajit20 if in case you are busy I can collab on this
@jatinsandilya in mean time can i work on this ?

**Comment by jatinsandilya** [comment]
@hrutik7 Feel free to take it up! :)

**Comment by manish-singh-bisht** [comment]
HI THERE, can i take this up.
