### ISSUE TITLE
Improve local setup experience, improve documentation and share feedback

### ISSUE THREAD

**Issue by jatinsandilya** [revertinc/revert#261]
We are looking for help on how we can improve the local development environment setup for Revert. 

**Purpose**
We are trying to make the initial developer experience better of when someone wants to setup Revert locally. 

**Requirements**
This is your first time setting up the project locally. 

**Try and do the following:**

1. Try to create a connection with Hubspot as per our docs at - https://docs.revert.dev but locally. 
2. List down all the steps you did along the way and see if if any of those steps are missing in the local setup documentation. Add it if required. 
3. Please share how else you would go about improving the setup experience. 

**Submission**
Create a PR that improves the documentation and makes the local setup easier.

**Comment by Nabhag8848** [comment]
Hey @jatinsandilya working on this. been setting up for a while and this is much needed.

**Comment by jatinsandilya** [comment]
@Nabhag8848 Love it! Please feel free to ask any questions on this issue or on the discord via DMs if needed. Assigning it to you! ❤️

**Comment by jatinsandilya** [comment]
@Nabhag8848 Are you still looking at this?

**Comment by Nabhag8848** [comment]
oops.i believe if someone else could take up this currently would be great. sorry for not letting you earlier  [wrote this from phone].

#### my laptop has been making an issue lately, not working and keeps on hanging, ordered new one. 

See you, will be back. once i fix things up.

**Comment by iamshabell** [comment]
@jatinsandilya I would love to take this up :)

**Comment by jatinsandilya** [comment]
@iamshabell thanks! Assigning it to you

**Comment by iamshabell** [comment]
> hey @iamshabell are you still working on it 
> I have already setup client as well as backend succesfully if you are busy in something i'll happy to take this up

hey @hrutik7 i was having problems with settin up my environment. So you could take this up.

**Comment by jatinsandilya** [comment]
@hrutik7 I'll assign this to you?

**Comment by hrutik7** [comment]
sure @jatinsandilya 
just saw your comment !

**Comment by jatinsandilya** [comment]
Assigned it to you! Lets goo 🚀
