### ISSUE TITLE
Use OpenStatus for Uptime monitoring

### ISSUE THREAD

**Issue by jatinsandilya** [revertinc/revert#288]
Use OpenStatus for uptime monitoring - https://github.com/openstatusHQ/openstatus and move away from Cronitor

**Comment by majjikishore007** [comment]
@jatinsandilya can I work on this issue, if it is not assigned to anyone

**Comment by majjikishore007** [comment]
@jatinsandilya  it would be more helpful if you could give some more information about this issue.

**Comment by jatinsandilya** [comment]
Turns out, it was very simple to setup and has been done now.  

The new uptime monitoring page is here: https://revert.openstatus.dev/ 🎉
