### ISSUE TITLE
[ISSUE-REVERT]: Error with first time run, database migrations

### ISSUE THREAD

**Issue by ashley-conpago** [revertinc/revert#399]
**Describe the bug**
following the steps in the base README.md for the local docker-compose example, running `docker-compose run db-seed` fails with the error:
```
PrismaClientKnownRequestError: 
Invalid `prisma.fieldMappings.createMany()` invocation in
/app/packages/backend/prisma/seed.ts:965:32

  962     });
  963 });
  964 
→ 965 await prisma.fieldMappings.createMany(
Foreign key constraint failed on the field: `fieldMappings_schema_id_fkey (index)`
    at Rn.handleRequestError (/app/node_modules/@prisma/client/runtime/library.js:174:7325)
    at Rn.handleAndLogRequestError (/app/node_modules/@prisma/client/runtime/library.js:174:6754)
    at Rn.request (/app/node_modules/@prisma/client/runtime/library.js:174:6344)
    at async main (/app/packages/backend/prisma/seed.ts:965:5) {
  code: 'P2003',
  clientVersion: '4.16.2',
  meta: { field_name: 'fieldMappings_schema_id_fkey (index)' }
}
npm ERR! Lifecycle script `db-seed:docker` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: @revertdotdev/backend@1.0.0 
npm ERR!   at location: /app/packages/backend 

```

If I continue and run `docker-compose up -d` the containers all start, no errors in the logs as far as I can see 
![image](https://github.com/revertinc/revert/assets/139291535/da2c75c3-8d52-4372-a2f8-002b81fec611)
http://localhost:3000 gives a blank screen, 2 errors in browser console

```
Error: @clerk/clerk-react: Missing publishableKey. You can get your key at https://dashboard.clerk.dev/last-active?path=api-keys.
    throwMissingPublishableKeyError thrower.ts:78
    c ClerkProvider.js:20
    React 7
    k scheduler.production.min.js:13
    A scheduler.production.min.js:14
react-dom.production.min.js:189:29

```

is the README missing a step to get/set that publishable key? I know I have one in revert dashboard and I tried putting that in frontend .env but it returns the same error anyway.

**To Reproduce**
1. run  `docker-compose run db-seed`

**Desktop (please complete the following information):**

-   OS: Ubuntu 22.04.3 LTS
-   Version: master at this commit: 974dfbce5b9801b43ce94256c917129a35c89e01

**Additional context**

**Comment by jatinsandilya** [comment]
@ashley-conpago Thanks for pointing this out! 

For the `client` package to work, we use Clerk for authentication and you'd need to setup an account on Clerk and use there publishable key in the `.env` for client as mentioned here (`REACT_APP_CLERK_PUBLISHABLE_KEY`) - 

https://github.com/revertinc/revert/blob/main/packages/client/.env.example

As mentioned on the error message, you can get the publishable key at https://dashboard.clerk.dev/ once you sign up at https://clerk.dev. 

We should make this easier than it is right now, I'm happy to work closely with you resolve this. 

Just hop on our [discord](https://discord.com/invite/q5K5cRhymW) and we can get you started quicker.

**Comment by jatinsandilya** [comment]
And re: the prisma error, did you run `docker-compose run db-seed` twice by any chance to get that error?

**Comment by ashley-conpago** [comment]
> And re: the prisma error, did you run docker-compose run db-seed twice by any chance to get that error?
pretty sure I didn't, but may have - I also nuked the containers/images/repo and started from scratch and got that error.
so if that is what causes it there was some state left over somewhere.

> We should make this easier than it is right now, I'm happy to work closely with you resolve this.
it's all good, just looks like we might need a small update to the README, just gotta make the instructions to run it the actual full instructions to run it.

will try out the stuff you mentioned, you can close this issue if you'd like if it's not actually a bug.

**Comment by jatinsandilya** [comment]
Sure @ashley-conpago ! let us know. 

Also ICYMI, we do have a cloud version that you could checkout at https://app.revert.dev/sign-up and then self host if you'd like.

**Comment by jatinsandilya** [comment]
Fixed.
