### ISSUE TITLE
[BUG]: Creation of App doesn't include PublicToken in db

### ISSUE THREAD

**Issue by Nabhag8848** [revertinc/revert#582]
**Describe the bug**
- This doesn't break anything in production but reason for this is previously we were creating all the apps when someone logins for the first time and `clerk/webhook` and didn't had a way to have publicToken which is probably the reason for not storing it before , Now that we create apps when required we can include publicToken for the environement directly in db.

**Expected behavior**
- Include pubilcToken in db

**Comment by PrateekPsingh** [comment]
Please assign me this issue so that i can work on it.

**Comment by Nabhag8848** [comment]
Closing as this wasn't required.
